CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE user_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    public_key TEXT NOT NULL,
    private_key_encrypted TEXT NOT NULL,
    algorithm VARCHAR(50) NOT NULL,
    key_size INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_user_keys_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_user_keys_user_id UNIQUE (user_id)
);

CREATE TABLE signatures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    original_text TEXT NOT NULL,
    text_hash VARCHAR(512) NOT NULL,
    signature_base64 TEXT NOT NULL,
    hash_algorithm VARCHAR(100) NOT NULL,
    signature_algorithm VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_signatures_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_signatures_public_id UNIQUE (public_id)
);

CREATE TABLE verification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signature_id BIGINT NOT NULL,
    provided_text TEXT,
    provided_signature_base64 TEXT,
    valid BOOLEAN NOT NULL,
    message VARCHAR(500),
    verified_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_verification_logs_signature FOREIGN KEY (signature_id) REFERENCES signatures (id)
);
